steps:
  # Build Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/rasadhana-app/ml-api-rasadhana", "."]

  # Push Docker image ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/rasadhana-app/ml-api-rasadhana"]

  # Deploy ke Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "ml-api-rasadhana"
      - "--image=gcr.io/rasadhana-app/ml-api-rasadhana"
      - "--platform=managed"
      - "--region=asia-southeast2"
      - "--allow-unauthenticated"
 
images:
  - "gcr.io/rasadhana-app/ml-api-rasadhana"

options:
  logging: CLOUD_LOGGING_ONLY
